spring.application.name=user-service
server.port=8081

spring.datasource.url=jdbc:postgresql://postgres:5432/userdb
spring.datasource.username=postgres
spring.datasource.password=raju

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata

spring.cloud.consul.host=consul
spring.cloud.consul.port=8500
spring.cloud.consul.discovery.register=true
spring.cloud.consul.discovery.health-check-path=/actuator/health

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Kafka Broker
spring.kafka.bootstrap-servers=kafka:9092

# Key serializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer

# Value serializer (we send JSON object)
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Optional but recommended
spring.kafka.producer.acks=all
spring.kafka.producer.retries=3